name: Build Spring Boot Application


on:
  push:
    branches:
      - main

  workflow_dispatch:


jobs:

  build:

    name: Compile and Package Jar

    runs-on: ubuntu-latest


    steps:

      # Download source code into runner
      - name: Checkout repository
        uses: actions/checkout@v4


      # Install Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven


      # Compile + Package Spring Boot application
      - name: Build Spring Boot Jar
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests


      # Verify generated jar
      - name: Check generated jar
        run: |
          ls -lh target/


      # Upload jar to GitHub artifact storage
      - name: Upload Jar Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: target/*.jar
